name: Assignment 5 Config

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
      - run:  mvn install -DskipTests -pl neo4j -am
      - run:  mvn -pl neo4j test -Dtest=org.hibernate.ogm.backendtck.storedprocedures.NamedParametersStoredProcedureCallTest#testResultSetDynamicCallWithResultClass
      - run:  mvn -pl neo4j edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=org.hibernate.ogm.backendtck.storedprocedures.NamedParametersStoredProcedureCallTest#testResultSetDynamicCallWithResultClass
